image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s settings.xml -Dmaven.repo.local=.m2/repository --batch-mode"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS verify
  except:
    - master
    - develop

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
    - develop